In [10]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Price for Each Food's Origin Country
data = pd.read_csv("global_street_food.csv")

country = data['Country'].unique().tolist()

results = []

for dt in country:
    country_data = data[data['Country'] == dt]

    total_food = country_data['Typical Price (USD)'].count()
    min_amount = country_data['Typical Price (USD)'].min()
    max_amount = country_data['Typical Price (USD)'].max()
    avg_amount = country_data['Typical Price (USD)'].mean()
    
    results.append({
        'Country': dt,
        'Total Food': total_food,
        'Min Typical Price': min_amount,
        'Max Typical Price': max_amount,
        'Average Typical Price': round(avg_amount,2),
    })

res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Average Typical Price', ascending=False)
res_df

,Country,Total Food,Min Typical Price,Max Typical Price,Average Typical Price
7,Lebanon,118,2.50,4.50,3.55
8,South Africa,58,3.50,3.50,3.50
6,Israel,49,3.00,3.00,3.00
10,Egypt,57,2.80,2.80,2.80
0,Japan,832,0.22,5.00,2.77
4,Turkey,650,0.20,4.99,2.62
2,USA,621,0.20,4.99,2.58
1,India,682,0.21,5.00,2.57
5,Mexico,660,0.20,5.00,2.57
3,Thailand,722,0.20,4.99,2.56
9,Nigeria,51,2.50,2.50,2.50

In [9]:
import pandas as pd

# Declaration
# Count Total Vegetarian Food for Each Origin Country
data = pd.read_csv("global_street_food.csv")

# Get all unique countries
country = data['Country'].unique().tolist()

# Prepare container for results
results = []

# Loop through each country
for dt in country:
    # Filter data for this country only
    country_data = data[data['Country'] == dt]

    # Count number of vegetarian foods
    total_veg_yes = country_data[country_data['Vegetarian'] == 'Yes'].shape[0]
    total_veg_no = country_data[country_data['Vegetarian'] == 'No'].shape[0]

    # Store result
    results.append({
        'Country': dt,
        'Total Vegetarian Food (Yes)': total_veg_yes,
        'Total Vegetarian Food (No)': total_veg_no
    })

# Convert result into DataFrame
res_df = pd.DataFrame(results)

# Sort the data by total vegetarian count in descending order
res_df = res_df.sort_values(by='Total Vegetarian Food (Yes)', ascending=False)
print(res_df)

         Country  Total Vegetarian Food (Yes)  Total Vegetarian Food (No)
3       Thailand                          476                         246
1          India                          469                         213
4         Turkey                          456                         194
5         Mexico                          448                         212
0          Japan                          334                         498
2            USA                          206                         415
10         Egypt                           57                           0
7        Lebanon                           56                          62
6         Israel                           49                           0
8   South Africa                            0                          58
9        Nigeria                            0                          51

In [5]:
import pandas as pd
from collections import Counter

# Descriptive Statistic - Analyzing Most Used Ingredient per Country
data = pd.read_csv("global_street_food.csv")

country_results = []

# Get all unique countries
for country in data['Country'].unique():
    country_data = data[data['Country'] == country] 
    all_ingredients = [] 
    
    # Find and Split Ingredient Call Each Country
    for ingredients in country_data['Ingredients'].dropna(): 
        ingredient_list = [i.strip().lower() for i in ingredients.split(',')]  
        all_ingredients.extend(ingredient_list)  
    
    # Count the frequency
    ingredient_counts = Counter(all_ingredients)
    
    # Get the most used ingredient
    if ingredient_counts:
        most_common_ingredient, count = ingredient_counts.most_common(1)[0]  
    else:
        most_common_ingredient, count = None, 0 
    
    country_results.append({
        'Country': country,
        'Most Common Ingredient': most_common_ingredient,
        'Total Used': count
    })

ingredient_per_country_df = pd.DataFrame(country_results)
print(ingredient_per_country_df)

         Country Most Common Ingredient  Total Used
0          Japan                  flour         321
1          India                 spices         469
2            USA                sausage         210
3       Thailand                   pork         246
4         Turkey                  dough         234
5         Mexico                 cheese         448
6         Israel              chickpeas          49
7        Lebanon                   meat          62
8   South Africa                  bread          58
9        Nigeria                   beef          51
10         Egypt                lentils          57

In [15]:
import pandas as pd

# Display settings
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 0)

# Descriptive Statistic - Count Total Food for Each Origin Country By Its Cooking Method
data = pd.read_csv("global_street_food.csv")

# Get all unique cooking method
countries = data['Country'].unique().tolist()
cooking_methods = data['Cooking Method'].unique().tolist()
# Get all unique countries
country = data['Country'].unique().tolist()

results = []
# Loop through each country
for dt in country:
    # Filter data for this country only
    country_data = data[data['Country'] == dt]
    result = {'Country': dt}

    # Loop through each cooking method
    for method in cooking_methods:
        total = country_data[country_data['Cooking Method'] == method].shape[0]
        result[method] = total

    results.append(result)

# Convert result into DataFrame
res_df = pd.DataFrame(results)

print(res_df)

         Country  Fried  Grilled  Stir-Fried  Assembled  Baked  Boiled/Grilled  Pan-Fried  Stewed  Boiled
0          Japan    233        0         278          0    271               0         50       0       0
1          India    230      213           0        239      0               0          0       0       0
2            USA    206      415           0          0      0               0          0       0       0
3       Thailand      0      246         235        241      0               0          0       0       0
4         Turkey      0      428           0          0    222               0          0       0       0
5         Mexico      0      437           0          0      0             223          0       0       0
6         Israel     49        0           0          0      0               0          0       0       0
7        Lebanon      0       62           0          0     56               0          0       0       0
8   South Africa      0        0           0          0      0               0          0      58       0
9        Nigeria      0       51           0          0      0               0          0       0       0
10         Egypt      0        0           0          0      0               0          0       0      57

In [3]:
import pandas as pd
from collections import Counter

# Descriptive Statistic - Analyzing Most Used Ingredient per Region
data = pd.read_csv("global_street_food.csv")

region_results = []

# Get all unique Region/City
for region in data['Region/City'].unique():
    region_data = data[data['Region/City'] == region] 
    all_ingredients = [] 
    
    # Find and Split Ingredient Call Each Region
    for ingredients in region_data['Ingredients'].dropna(): 
        ingredient_list = [i.strip().lower() for i in ingredients.split(',')]  
        all_ingredients.extend(ingredient_list)  
    
    # Count the frequency
    ingredient_counts = Counter(all_ingredients)
    
    # Get the most used ingredient
    if ingredient_counts:
        most_common_ingredient, count = ingredient_counts.most_common(1)[0]  
    else:
        most_common_ingredient, count = None, 0 
    
    region_results.append({
        'Region/City': region,
        'Most Common Ingredient': most_common_ingredient,
        'Total Used': count
    })

ingredient_per_region_df = pd.DataFrame(region_results)
print(ingredient_per_region_df)

     Region/City Most Common Ingredient  Total Used
0          Osaka                octopus         233
1         Mumbai                 potato         230
2          Texas                 batter         206
3        Kolkata              flatbread         213
4        Bangkok           rice noodles         235
5          Delhi               semolina         239
6          Kyoto                  flour         217
7         Ankara                  dough         234
8          Izmir        lamb intestines         194
9      Ayutthaya                   roti         241
10         Tokyo                noodles         278
11        Puebla               tortilla         225
12   Guadalajara                   corn         223
13      New York                sausage         210
14   Mexico City                   pork         212
15      Istanbul                  flour         222
16    Chiang Mai                   pork         246
17  Philadelphia                   beef         205
18      Tel Aviv              chickpeas          49
19       Tripoli              flatbread          56
20        Beirut                   meat          62
21     Hiroshima                cabbage          50
22        Durban                  bread          58
23         Lagos                   beef          51
24         Cairo                lentils          57

In [5]:
import pandas as pd

# Display settings
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 0)

# Descriptive Statistic - Group by Country, Find Average Price and Most Used Cooking Method
data = pd.read_csv("global_street_food.csv")

# Get all unique countries
country = data['Country'].unique().tolist()

results = []
for dt in country:
    # Filter data for this country only
    country_data = data[data['Country'] == dt]
    result = {'Country': dt}

    # Get Typical Price (USD) average for the country
    result['Average Typical Price (USD)'] = country_data['Typical Price (USD)'].mean()

    # Get Most Used Cooking Method for the country
    result['Most Used Cooking Method'] = country_data['Cooking Method'].mode().iloc[0]
    results.append(result)

res_df = pd.DataFrame(results)
print(res_df)

         Country  Average Typical Price (USD) Most Used Cooking Method
0          Japan                     2.770204               Stir-Fried
1          India                     2.571085                Assembled
2            USA                     2.578728                  Grilled
3       Thailand                     2.555360                  Grilled
4         Turkey                     2.621831                  Grilled
5         Mexico                     2.565894                  Grilled
6         Israel                     3.000000                    Fried
7        Lebanon                     3.550847                  Grilled
8   South Africa                     3.500000                   Stewed
9        Nigeria                     2.500000                  Grilled
10         Egypt                     2.800000                   Boiled

In [3]:
import pandas as pd

# Display settings
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 0)

# Descriptive Statistic - Most Expensive and Cheapest Food Per Country
data = pd.read_csv("global_street_food.csv")

# Get all unique countries
country = data['Country'].unique().tolist()

results = []
for dt in country:
    # Filter data for this country only
    country_data = data[data['Country'] == dt]
    result = {'Country': dt}

    # Get Most Expensive Food for the country
    max_idx = country_data['Typical Price (USD)'].idxmax()
    result['Most Expensive Food'] = country_data.loc[max_idx, 'Dish Name']
    result['Most Expensive Price (USD)'] = country_data.loc[max_idx, 'Typical Price (USD)']

    # Get Cheapest Food for the country
    min_idx = country_data['Typical Price (USD)'].idxmin()
    result['Cheapest Food'] = country_data.loc[min_idx, 'Dish Name']
    result['Cheapest Price (USD)'] = country_data.loc[min_idx, 'Typical Price (USD)']

    results.append(result)

res_df = pd.DataFrame(results)
print(res_df)

         Country Most Expensive Food  Most Expensive Price (USD)       Cheapest Food  Cheapest Price (USD)
0          Japan             Taiyaki                        5.00            Takoyaki                  0.22
1          India            Vada Pav                        5.00           Pani Puri                  0.21
2            USA  Philly Cheesesteak                        4.99  Philly Cheesesteak                  0.20
3       Thailand        Roti Sai Mai                        4.99            Moo Ping                  0.20
4         Turkey             Gözleme                        4.99             Kokoreç                  0.20
5         Mexico               Elote                        5.00     Tacos al Pastor                  0.20
6         Israel             Falafel                        3.00             Falafel                  3.00
7        Lebanon            Shawarma                        4.50            Manakish                  2.50
8   South Africa          Bunny Chow                        3.50          Bunny Chow                  3.50
9        Nigeria                Suya                        2.50                Suya                  2.50
10         Egypt             Koshari                        2.80             Koshari                  2.80

In [4]:
import pandas as pd

# Display settings
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 0)

# Declaration
# Descriptive Statistic : Total Street Food, Average Price, Most Cooking Method, and Country By Vegetarian Category
data = pd.read_csv("global_street_food.csv")

# Get all unique vegetarian categories
vegetarian = data['Vegetarian'].unique().tolist()

# Prepare container for results
results = []

# Loop through each vegetarian category
for dt in vegetarian:
    # Filter data for this category only
    veg_data = data[data['Vegetarian'] == dt]

    # Count total foods
    total_count = veg_data.shape[0]

    # Calculate average price
    avg_price = veg_data['Typical Price (USD)'].mean()

    # Find most common cooking method
    most_cooking_method = veg_data['Cooking Method'].mode()[0] if not veg_data['Cooking Method'].mode().empty else None

    # Find most common country
    most_country = veg_data['Country'].mode()[0] if not veg_data['Country'].mode().empty else None

    # Store result
    results.append({
        'Vegetarian': dt,
        'Total Food Count': total_count,
        'Average Price (USD)': avg_price,
        'Most Cooking Method': most_cooking_method,
        'Most Country': most_country
    })

# Convert result into DataFrame
res_df = pd.DataFrame(results)

# Sort the data by total food count in descending order
res_df = res_df.sort_values(by='Total Food Count', ascending=False)

print(res_df)

  Vegetarian  Total Food Count  Average Price (USD) Most Cooking Method Most Country
1        Yes              2551             2.631470               Baked     Thailand
0         No              1949             2.691406             Grilled        Japan

In [5]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic : Analyzed Price, Total Vegan Food, and Country With Most Food For Specific Cooking Method
data = pd.read_csv("global_street_food.csv")

country = data['Cooking Method'].unique().tolist()

results = []

for dt in country:
    country_data = data[data['Cooking Method'] == dt]

    total_food = country_data['Typical Price (USD)'].count()
    min_amount = country_data['Typical Price (USD)'].min()
    max_amount = country_data['Typical Price (USD)'].max()
    avg_amount = country_data['Typical Price (USD)'].mean()

    # Count Vegetarian and Non-Vegetarian Food
    total_vegetarian_yes = country_data[country_data['Vegetarian'] == 'Yes'].shape[0]
    total_vegetarian_no = country_data[country_data['Vegetarian'] == 'No'].shape[0]

    # Get Most Found Country in Each Cooking Method
    most_found_country = country_data['Country'].mode()
    most_found_country = most_found_country.iloc[0] if not most_found_country.empty else None
    
    results.append({
        'Cooking Method': dt,
        'Total Food': total_food,
        'Min Typical Price': min_amount,
        'Max Typical Price': max_amount,
        'Average Typical Price': round(avg_amount,2),
        'Total Vegetarian (Yes)': total_vegetarian_yes,
        'Total Non-Vegetarian (No)': total_vegetarian_no,
        'Most Found Country': most_found_country
    })

res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Average Typical Price', ascending=False)
res_df

,Cooking Method,Total Food,Min Typical Price,Max Typical Price,Average Typical Price,Total Vegetarian (Yes),Total Non-Vegetarian (No),Most Found Country
6,Pan-Fried,50,5.00,5.00,5.00,0,50,Japan
7,Stewed,58,3.50,3.50,3.50,0,58,South Africa
8,Boiled,57,2.80,2.80,2.80,57,0,Egypt
2,Stir-Fried,513,0.20,4.96,2.72,298,215,Japan
5,Boiled/Grilled,223,0.20,5.00,2.71,223,0,Mexico
0,Fried,718,0.22,5.00,2.66,485,233,Japan
1,Grilled,1852,0.20,4.99,2.62,459,1393,Mexico
3,Assembled,480,0.21,4.99,2.53,480,0,Thailand
4,Baked,549,0.22,5.00,2.50,549,0,Japan